version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sass
    versions:
    - 1.32.11
  - dependency-name: ioredis
    versions:
    - 4.25.0
  - dependency-name: eslint
    versions:
    - 7.23.0
